#%RAML 1.0 NamedExample
value:
  id: 1
  title: "Moana"
  year: 2016
  genre: "Animación"
  director: "Ron Clements y John Musker"
  cast:
    - 
      id: 1
      name: "Auli'i Cravalho"
    - 
      id: 2
      name: "Dwayne Johnson"